{
  "title": "Sample Puzzle",
  "by": "By Line",
  "clues": [
	  { "d": "A", "n":2, "x":8, "y":1, "a":"DUMBBELL", "c":"A nincompoop"},
	  { "d": "A", "n":4, "x":18, "y":1, "a":"CHAIR", "c":"Rocks on the front porch"},
	  { "d": "A", "n":6, "x":0, "y":3, "a":"TELEVISION", "c":"Was once only black-and-white"},
	  { "d": "A", "n":8, "x":17, "y":4, "a":"POKE", "c":"What a pig is in, or diced fish in Maui"},
	  { "d": "A", "n":9, "x":5, "y":7, "a":"WAKLEDINTO", "c":"Entered an ambush, 2 words"},
	  { "d": "A", "n":12, "x":15, "y":8, "a":"OBJECT", "c":"To disagree, legally"},
	  { "d": "A", "n":14, "x":8, "y":9, "a":"STATUE", "c":"Lincoln in the memorial"},
	  { "d": "A", "n":16, "x":18, "y":10, "a":"CEILING", "c":"Upper limit"},
	  { "d": "A", "n":19, "x":12, "y":12, "a":"CRUSHING", "c":"Really, really liking someone, anonymously"},
	  { "d": "A", "n":20, "x":6, "y":14, "a":"WHEELER", "c":"A type of dealer"},
	  { "d": "A", "n":21, "x":18, "y":14, "a":"BBGUN", "c":"All Ralphie wanted for Christmas, 2 words"},
	  { "d": "A", "n":22, "x":9, "y":17, "a":"FRIEND", "c":"bestie, dog to a man"},
	  { "d": "A", "n":23, "x":7, "y":19, "a":"FELLON", "c":"Hard times mechanism, 2 words"},
	  { "d": "D", "n":1, "x":20, "y":0, "a":"JAMMED", "c":"freely associated on a guitar"},
	  { "d": "D", "n":2, "x":8, "y":1, "a":"DOOR", "c":"A type of bell"},
	  { "d": "D", "n":3, "x":11, "y":1, "a":"BUMPEDINTO", "c":"Coincidental meeting of friends, 2 words"},
	  { "d": "D", "n":5, "x":5, "y":2, "a":"KICK", "c":"Dean Martin got this in the head"},
	  { "d": "D", "n":7, "x":18, "y":3, "a":"BOTTLE", "c":"A type of rocket"},
	  { "d": "D", "n":10, "x":13, "y":7, "a":"TREE", "c":"A family, hall, or maple"},
	  { "d": "D", "n":11, "x":24, "y":7, "a":"WEIGHT", "c":"The world on your shoulders"},
	  { "d": "D", "n":13, "x":16, "y":8, "a":"BROTHER", "c":"One Doobie (or Grim) to another"},
	  { "d": "D", "n":14, "x":8, "y":9, "a":"SLAMMED", "c":"Way too busy"},
	  { "d": "D", "n":15, "x":22, "y":9, "a":"SIBLING", "c":"A type of rivalry"},
	  { "d": "D", "n":16, "x":18, "y":10, "a":"CAN", "c":"Is capable of an action"},
	  { "d": "D", "n":17, "x":10, "y":11, "a":"TABLE", "c":"To defer judgement on a motion"},
	  { "d": "D", "n":18, "x":14, "y":11, "a":"PUNCHED", "c":"Early computer programming card"},
	  { "d": "D", "n":19, "x":12, "y":12, "a":"CART", "c":"It was put before the horse"},
	  { "d": "D", "n":21, "x":18, "y":14, "a":"BOARD", "c":"Has a chairman"},
	  { "d": "D", "n":22, "x":9, "y":17, "a":"FALL", "c":"Opposite of spring"}
  ]
}
